import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { currentTrendsUi } from "./current-trends-ui.mjs";

// Failure and delay routes below are explicit test conditions, never successful auth/save mocks.
export async function browserUiChecks({ page, context, origin, db, call, stage, capture }) {
  const email = "browser-ui@example.test";
  const password = "UI-synthetic-" + randomBytes(20).toString("hex");
  const visible = async (text) => page.getByText(text, { exact: false }).first().waitFor({ state: "visible" });
  const rate = () => db.prepare('DELETE FROM "rateLimit"').run();
  const signIn = async (pwd, loginEmail = email) => {
    await rate();
    await page.getByRole("form", { name: "Sign in", exact: true }).getByLabel("Email", { exact: true }).fill(loginEmail);
    await page.getByRole("form", { name: "Sign in", exact: true }).getByLabel("Password", { exact: true }).fill(pwd);
    await page.getByRole("form", { name: "Sign in", exact: true }).getByRole("button", { name: "Sign in", exact: true }).click();
  };
  stage("UI signup and verification from private D1 outbox");
  await page.goto(origin);
  await page.getByRole("button", { name: "Create test login", exact: true }).click();
  await page.getByLabel("Test name", { exact: true }).fill("Synthetic UI visitor");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  stage("Signup form screenshots and geometry");
  assert.equal(await page.getByLabel("Password", { exact: true }).getAttribute("type"), "password");
  await page.getByRole("heading", { name: "Create test login", exact: true }).waitFor();
  await capture("signup");
  await rate();
  stage("UI signup submit");
  await page.getByRole("form", { name: "Create test login" }).getByRole("button", { name: "Create test login" }).click();
  stage("UI signup acceptance notice");
  await visible("No email was delivered.");
  const user = await db.prepare("SELECT id FROM user WHERE email = ?").bind(email).first();
  const mail = await db.prepare("SELECT url FROM local_outbox WHERE authUserId = ? AND kind = 'verify' ORDER BY id DESC LIMIT 1").bind(user.id).first();
  assert.equal(new URL(mail.url).origin, origin);
  stage("UI signup verification callback");
  await page.goto(mail.url);
  await page.goto(origin);
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  await visible("Nothing has been saved automatically.");
  const guestSelection = await page.evaluate(() => sessionStorage.getItem("pendingSpotId"));
  assert.ok(guestSelection);
  stage("UI invalid password then real sign-in");
  await signIn("Wrong-synthetic-password");
  await visible("Invalid email or password");
  await signIn(password);
  await page.getByRole("button", { name: "Create new account", exact: true }).waitFor();
  assert.equal(await page.evaluate(() => sessionStorage.getItem("pendingSpotId")), guestSelection);
  const provision = page.waitForRequest((req) => new URL(req.url()).pathname === "/api/account/new");
  await page.getByRole("button", { name: "Create new account", exact: true }).click();
  assert.ok((await provision).headers()["x-localley-session-id"]);
  stage("Actual preference controls use native ownership and persist confirmed choices");
  await page.getByRole("button", { name: "Email preferences", exact: true }).click();
  const marketing = page.getByRole("switch", { name: "Marketing Emails", exact: true });
  await marketing.waitFor();
  assert.equal(await marketing.getAttribute("aria-checked"), "false");
  await capture("preferences-off");
  const preferenceRequest = page.waitForRequest(req => req.method() === "PUT" && new URL(req.url()).pathname === "/api/user/email-preferences");
  await marketing.focus();
  await page.keyboard.press("Space");
  assert.ok((await preferenceRequest).headers()["x-localley-session-id"]);
  await visible("Email preferences saved.");
  assert.equal((await call("/api/user/email-preferences")).data.preferences.marketing, true);
  await capture("preferences-saved");
  await page.reload();
  await page.getByRole("button", { name: "Email preferences", exact: true }).click();
  await marketing.waitFor();
  assert.equal(await marketing.getAttribute("aria-checked"), "true");
  await page.route("**/api/user/email-preferences", route => route.fulfill({ status: 503, contentType: "application/json", body: '{"error":"Synthetic failure"}' }));
  await marketing.click();
  await visible("The update could not be confirmed.");
  assert.equal(await page.getByRole("switch").count(), 0);
  await capture("preferences-error");
  await page.unroute("**/api/user/email-preferences");
  await page.getByRole("button", { name: "Retry email preferences", exact: true }).click();
  await marketing.waitFor();
  assert.equal(await marketing.getAttribute("aria-checked"), "true");
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await visible("No saved places yet.");
  assert.equal((await call("/api/spots/save")).data.spots.length, 0);
  stage("Current-week UI preserves unknown counts, failures and freshness without source media");
  await currentTrendsUi({ page, capture });
  stage("Native mapping deadline clears private identity and permits an explicit retry");
  const stalled = [];
  await page.route("**/api/session", route => { stalled.push(route); });
  await page.reload();
  await page.getByRole("button", { name: "Check session again", exact: true }).waitFor({ timeout: 30000 });
  assert.equal(await page.locator(".identity").count(), 0);
  await capture("account-timeout");
  await page.unroute("**/api/session");
  await Promise.all(stalled.map(route => route.abort().catch(() => {})));
  await page.getByRole("button", { name: "Check session again", exact: true }).click();
  await page.getByRole("button", { name: "Sign out", exact: true }).waitFor();
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await visible("No saved places yet.");
  stage("Signed-in empty collection screenshots and measured controls");
  await capture("empty");
  stage("UI real save, refresh and unsave");
  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await capture("long-name");
  const saveRequest = page.waitForRequest((req) => req.method() === "POST" && new URL(req.url()).pathname === "/api/spots/save");
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  assert.ok((await saveRequest).headers()["x-localley-session-id"]);
  await page.getByRole("article").first().getByRole("button", { name: /^Remove / }).waitFor();
  assert.equal(await page.evaluate(() => sessionStorage.getItem("pendingSpotId")), null);
  await page.reload();
  await page.getByRole("article").first().getByRole("button", { name: /^Remove / }).waitFor();
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await page.getByRole("article").getByRole("button", { name: /^Remove / }).click();
  await visible("No saved places yet.");

  stage("Desktop real save and remove, signed-in Korean collection screenshots");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await page.getByRole("article").nth(1).getByRole("button", { name: /^Save / }).click();
  await page.getByRole("article").nth(1).getByRole("button", { name: /^Remove / }).waitFor();
  await page.reload();
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await page.getByRole("article").getByRole("button", { name: /^Remove / }).waitFor();
  assert.equal((await call("/api/spots/save")).data.spots.length, 1);
  await capture("saved");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole("article").getByRole("button", { name: /^Remove / }).click();
  await visible("No saved places yet.");
  assert.equal((await call("/api/spots/save")).data.spots.length, 0);
  await page.setViewportSize({ width: 390, height: 844 });

  stage("UI stale Alice response after Bob cookie switch: delayed native response");
  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  await page.getByRole("article").first().getByRole("button", { name: /^Remove / }).waitFor();
  const previousSave = (await call("/api/spots/save")).data.spots[0];
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Signed out.");
  await page.getByRole("article").nth(1).getByRole("button", { name: /^Save / }).click();
  const accountSelection = await page.evaluate(() => sessionStorage.getItem("pendingSpotId"));
  assert.ok(accountSelection);
  await signIn(password);
  await visible(email);
  assert.equal(await page.evaluate(() => sessionStorage.getItem("pendingSpotId")), accountSelection);
  const previousSession = (await call("/api/session")).data;
  let releaseOld;
  let receivedOld;
  const oldResponse = new Promise((done) => { receivedOld = done; });
  const oldDelay = new Promise((done) => { releaseOld = done; });
  let delayOnce = true;
  const delayedSaved = async (route) => {
    if (!delayOnce || route.request().method() !== "GET") return route.continue();
    delayOnce = false;
    const response = await route.fetch();
    assert.equal(route.request().headers()["x-localley-session-id"], previousSession.sessionId);
    receivedOld();
    await oldDelay;
    await route.fulfill({ response }).catch(() => {});
  };
  await page.route("**/api/spots/save", delayedSaved);
  await page.reload({ waitUntil: "domcontentloaded" });
  await oldResponse;
  const other = await context.newPage();
  await other.goto(origin);
  // Create a second real user in this tab. No token or cookie injection authenticates it.
  const otherEmail = "browser-cross-tab@example.test";
  const otherPassword = "Other-ui-" + randomBytes(20).toString("hex");
  await rate();
  const created = await other.evaluate(async ({ email, password }) => {
    const response = await fetch("/api/auth/sign-up/email", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Synthetic Bob", email, password }) });
    return { status: response.status, data: await response.json() };
  }, { email: otherEmail, password: otherPassword });
  assert.equal(created.status, 200);
  const otherMail = await db.prepare("SELECT url FROM local_outbox WHERE authUserId = ? AND kind = 'verify' ORDER BY id DESC LIMIT 1").bind(created.data.user.id).first();
  assert.equal(new URL(otherMail.url).origin, origin);
  await other.goto(otherMail.url);
  await other.goto(origin);
  await rate();
  const switched = await other.evaluate(async ({ email, password, expected, spotId }) => {
    const send = (path, body, session) => fetch(path, { method: "POST", headers: { "Content-Type": "application/json", ...(session ? { "x-localley-session-id": session } : {}) }, body: JSON.stringify(body) });
    const login = await send("/api/auth/sign-in/email", { email, password });
    const stale = await send("/api/spots/save", { spotId }, expected);
    const staleRead = await fetch("/api/spots/save?spotId=" + spotId, { headers: { "x-localley-session-id": expected } });
    const data = await staleRead.json();
    return { login: login.status, stale: stale.status, code: (await stale.json()).error.code,
      staleRead: staleRead.status, readCode: data.error?.code, hasSaved: Object.hasOwn(data, "saved") };
  }, { email: otherEmail, password: otherPassword, expected: previousSession.sessionId, spotId: previousSave.spot_id });
  assert.deepEqual(switched, { login: 200, stale: 409, code: "session_changed", staleRead: 409, readCode: "session_changed", hasSaved: false });
  await page.bringToFront();
  await page.evaluate(() => window.dispatchEvent(new Event("focus")));
  await visible(otherEmail);
  assert.equal(await page.evaluate(() => sessionStorage.getItem("pendingSpotId")), null);
  assert.equal(new URL(page.url()).searchParams.get("pendingSpotId"), null);
  assert.equal(await page.getByRole("button", { name: /^Continue saving/ }).count(), 0);
  releaseOld();
  await page.unroute("**/api/spots/save", delayedSaved);
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  assert.equal(await page.getByRole("article").count(), 0);
  assert.equal(await page.getByText(email, { exact: true }).count(), 0);
  await other.close();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Signed out.");
  await signIn(password);
  await visible(email);
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await page.getByRole("article").getByRole("button", { name: /^Remove / }).click();
  await visible("No saved places yet.");

  stage("In-flight UI mutation at logout then Bob login: delayed native dispatch with current cookie");
  const mutationSession = (await call("/api/session")).data;
  const countRows = async (table) => (await db.prepare(`SELECT count(*) AS n FROM ${table}`).first()).n;
  const beforeRows = await countRows("saved_spots");
  const beforeEvents = await countRows("application_outbox");
  let releaseMutation;
  let receiveMutation;
  const mutationReceived = new Promise((done) => { receiveMutation = done; });
  const mutationDelay = new Promise((done) => { releaseMutation = done; });
  let delivered;
  const delivery = new Promise((done) => { delivered = done; });
  const delayedMutation = async (route) => {
    if (route.request().method() !== "POST") return route.continue();
    const expected = route.request().headers()["x-localley-session-id"];
    const body = route.request().postDataJSON();
    receiveMutation({ expected, body });
    await mutationDelay;
    // This explicit network-delay condition delivers the original body/header with the current real cookie.
    // The cookie comes only from successful native Better Auth login, never a fabricated credential.
    const cookies = await context.cookies(origin);
    const headers = { ...route.request().headers(), cookie: cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join("; ") };
    const response = await route.fetch({ headers });
    delivered({ status: response.status(), data: await response.json() });
    await route.fulfill({ response }).catch(() => {});
  };
  await page.route("**/api/spots/save", delayedMutation);
  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  const pendingMutation = await mutationReceived;
  assert.equal(pendingMutation.expected, mutationSession.sessionId);
  assert.deepEqual(pendingMutation.body, { spotId: previousSave.spot_id });
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Signed out.");
  await signIn(otherPassword, otherEmail);
  await visible(otherEmail);
  releaseMutation();
  const rejected = await delivery;
  assert.equal(rejected.status, 409);
  assert.equal(rejected.data.error.code, "session_changed");
  assert.equal(await countRows("saved_spots"), beforeRows);
  assert.equal(await countRows("application_outbox"), beforeEvents);
  assert.equal(await page.getByText(email, { exact: true }).count(), 0);
  await page.unroute("**/api/spots/save", delayedMutation);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Signed out.");
  await signIn(password);
  await visible(email);

  stage("UI quota and tombstone from real D1 fixtures");
  const session = (await call("/api/session")).data;
  await db.prepare("UPDATE owner_limits SET savedSpotLimit = 0 WHERE ownerId = ?").bind(session.ownerId).run();
  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  await visible("You've reached your saved spots limit.");
  await db.prepare("UPDATE owner_limits SET savedSpotLimit = 10 WHERE ownerId = ?").bind(session.ownerId).run();
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  await page.getByRole("article").first().getByRole("button", { name: /^Remove / }).waitFor();
  const saved = (await call("/api/spots/save")).data.spots[0];
  await db.prepare("UPDATE spots SET visible = 0 WHERE id = ?").bind(saved.spot_id).run();
  await page.reload();
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await visible("This place is no longer in the catalog.");
  await page.getByRole("article").getByRole("button", { name: /^Remove / }).click();
  await visible("No saved places yet.");
  await db.prepare("UPDATE spots SET visible = 1 WHERE id = ?").bind(saved.spot_id).run();

  stage("UI failed saved refresh is not false empty: injected HTTP 503");
  const failedRead = async (route) => route.request().method() === "GET"
    ? route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: { code: "database_error", message: "Synthetic read failure" } }) })
    : route.continue();
  await page.route("**/api/spots/save", failedRead);
  await page.reload();
  await page.getByRole("button", { name: "Saved places", exact: true }).click();
  await visible("Could not refresh saved places.");
  assert.equal(await page.getByText("No saved places yet.", { exact: false }).count(), 0);
  await capture("error");
  await page.unroute("**/api/spots/save", failedRead);
  await page.getByRole("button", { name: "Retry saved places" }).click();
  await visible("No saved places yet.");

  stage("UI catalog loading and error: injected delay and HTTP 503");
  let release;
  const pause = new Promise((done) => { release = done; });
  const delayedCatalog = async (route) => { await pause; await route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: { message: "Synthetic catalog failure" } }) }); };
  await page.route("**/api/spots?*", delayedCatalog);
  await page.reload({ waitUntil: "domcontentloaded" });
  await visible("Loading catalog...");
  release();
  await visible("Synthetic catalog failure");
  await page.unroute("**/api/spots?*", delayedCatalog);
  await page.getByRole("button", { name: "Retry catalog" }).click();
  await page.getByRole("article").first().waitFor();
  await db.prepare("UPDATE spots SET visible = 0").run();
  await page.reload();
  await visible("No test places are available.");
  await db.prepare("UPDATE spots SET visible = 1").run();

  stage("UI failed sign-out hides private state: injected HTTP 503");
  const failedLogout = (route) => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ message: "Synthetic sign-out failure" }) });
  await page.route("**/api/auth/sign-out", failedLogout);
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Sign-out failed. Private places stay hidden.");
  assert.equal((await call("/api/session")).status, 200);
  assert.equal(await page.getByText("Signed out.", { exact: false }).count(), 0);
  assert.equal(await page.getByText(email, { exact: true }).count(), 0);
  await page.unroute("**/api/auth/sign-out", failedLogout);
  await page.getByRole("button", { name: "Retry sign-out" }).click();
  await visible("Signed out.");
  assert.equal((await call("/api/session")).status, 401);

  stage("Guest selection survives login and clears on explicit logout");
  await page.reload();
  await visible("Signed out.");
  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await page.getByRole("article").first().getByRole("button", { name: /^Save / }).click();
  const logoutSelection = await page.evaluate(() => sessionStorage.getItem("pendingSpotId"));
  assert.ok(logoutSelection);
  await signIn(password);
  await visible(email);
  assert.equal(await page.evaluate(() => sessionStorage.getItem("pendingSpotId")), logoutSelection);
  const oldCookies = await context.cookies();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Signed out.");
  assert.equal(await page.evaluate(() => sessionStorage.getItem("pendingSpotId")), null);
  assert.equal(new URL(page.url()).searchParams.get("pendingSpotId"), null);
  assert.equal(await page.getByRole("button", { name: /^Continue saving/ }).count(), 0);
  stage("UI reset form with real token and revoked cookie");
  await page.getByRole("button", { name: "Forgot password?" }).click();
  await page.getByLabel("Email", { exact: true }).fill(email);
  stage("Password reset request screenshots and geometry");
  await page.getByRole("heading", { name: "Request password reset", exact: true }).waitFor();
  await capture("reset-request");
  await rate();
  await page.getByRole("form", { name: "Request password reset" }).getByRole("button", { name: "Request password reset" }).click();
  await visible("its reset link stays in the private local test outbox.");
  const reset = await db.prepare("SELECT url FROM local_outbox WHERE authUserId = ? AND kind = 'reset' ORDER BY id DESC LIMIT 1").bind(user.id).first();
  assert.equal(new URL(reset.url).origin, origin);
  await page.goto(reset.url);
  const newPassword = "New-ui-" + randomBytes(20).toString("hex");
  await page.getByLabel("New password", { exact: true }).fill(newPassword);
  stage("Actual reset token form screenshots and geometry");
  assert.equal(await page.getByLabel("New password", { exact: true }).getAttribute("type"), "password");
  await page.getByRole("heading", { name: "Reset password", exact: true }).waitFor();
  await capture("reset");
  stage("UI reset form with real token and revoked cookie");
  await page.getByRole("form", { name: "Reset password", exact: true }).getByRole("button", { name: "Reset password", exact: true }).click();
  await visible("Password reset confirmed.");
  await context.addCookies(oldCookies);
  assert.equal((await call("/api/session")).status, 401);
  await signIn(password);
  await visible("Invalid email or password");
  await signIn(newPassword);
  await visible(email);
  stage("Signed-in actual reset token form heading and geometry");
  await rate();
  assert.equal((await call("/api/auth/request-password-reset", "POST", { email, redirectTo: origin + "/?view=reset" })).status, 200);
  const signedInReset = await db.prepare("SELECT url FROM local_outbox WHERE authUserId = ? AND kind = 'reset' ORDER BY id DESC LIMIT 1").bind(user.id).first();
  assert.equal(new URL(signedInReset.url).origin, origin);
  await page.goto(signedInReset.url);
  await visible(email);
  await page.getByRole("form", { name: "Reset password", exact: true }).waitFor();
  assert.equal(await page.getByLabel("New password", { exact: true }).getAttribute("type"), "password");
  await capture("reset-signed-in");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await visible("Signed out.");
}
