/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.preview.template.jsonc --include-runtime=false --strict-vars=false --env-interface=PreviewEnv preview-configuration.d.ts` (hash: f46eff06d513c30fc1d6ff938ad5d4e8)
interface __BaseEnv_PreviewEnv {
	DB: D1Database;
	NATIVE_EMAIL: SendEmail;
	ASSETS: Fetcher;
	APP_MODE: string;
	LOCAL_PROOF: string;
	AUTH_BASE_URL: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	BETTER_AUTH_SECRET: string;
	CLAIM_SECRET: string;
	PREVIEW_ALLOWED_EMAILS: string;
	ACCESS_SERVICE_CLIENT_CN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_PreviewEnv {}
}
interface PreviewEnv extends __BaseEnv_PreviewEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_MODE" | "LOCAL_PROOF" | "AUTH_BASE_URL" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "BETTER_AUTH_SECRET" | "CLAIM_SECRET" | "PREVIEW_ALLOWED_EMAILS" | "ACCESS_SERVICE_CLIENT_CN">> {}
}
