// Generated by scripts/generate-geography-snapshot.ts. Do not edit manually.
export const GEOGRAPHY_MANIFEST_FINGERPRINT = "f43b08ec28f6cdbd37fb9aa8b420fd6e4ce44f07f7f3405f6ccf33f432b7ba5e" as const;

export const GENERATED_DESTINATIONS = [
  {
    "slug": "seoul",
    "name": "Seoul",
    "countryCode": "KR",
    "center": {
      "lat": 37.5665,
      "lng": 126.978
    },
    "timezone": "Asia/Seoul",
    "currency": "KRW",
    "languages": [
      "ko",
      "en"
    ],
    "ring": 1,
    "isEnabled": true,
    "localAreaSlugs": [
      "hongdae",
      "itaewon",
      "gangnam",
      "myeongdong",
      "insadong",
      "bukchon",
      "ikseon-dong",
      "seongsu-dong",
      "yeonnam-dong",
      "mangwon",
      "euljiro",
      "jongno",
      "sinchon",
      "samcheong-dong",
      "incheon-airport-area"
    ]
  },
  {
    "slug": "tokyo",
    "name": "Tokyo",
    "countryCode": "JP",
    "center": {
      "lat": 35.6762,
      "lng": 139.6503
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 1,
    "isEnabled": true,
    "localAreaSlugs": [
      "shibuya",
      "shinjuku",
      "harajuku",
      "shimokitazawa",
      "nakameguro",
      "daikanyama",
      "asakusa",
      "ginza",
      "roppongi",
      "koenji",
      "kichijoji",
      "yanaka",
      "tsukiji",
      "akihabara",
      "ebisu"
    ]
  },
  {
    "slug": "bangkok",
    "name": "Bangkok",
    "countryCode": "TH",
    "center": {
      "lat": 13.7563,
      "lng": 100.5018
    },
    "timezone": "Asia/Bangkok",
    "currency": "THB",
    "languages": [
      "th",
      "en"
    ],
    "ring": 1,
    "isEnabled": true,
    "localAreaSlugs": [
      "sukhumvit",
      "thonglor",
      "ekkamai",
      "ari",
      "chatuchak",
      "silom",
      "sathorn",
      "chinatown",
      "khao-san",
      "rattanakosin",
      "phra-khanong",
      "on-nut",
      "ratchada",
      "pratunam"
    ]
  },
  {
    "slug": "singapore",
    "name": "Singapore",
    "countryCode": "SG",
    "center": {
      "lat": 1.3521,
      "lng": 103.8198
    },
    "timezone": "Asia/Singapore",
    "currency": "SGD",
    "languages": [
      "en",
      "zh",
      "ms",
      "ta"
    ],
    "ring": 1,
    "isEnabled": true,
    "localAreaSlugs": [
      "tiong-bahru",
      "jalan-besar",
      "little-india",
      "chinatown",
      "kampong-glam",
      "holland-village",
      "dempsey-hill",
      "geylang",
      "east-coast",
      "katong",
      "bugis",
      "clarke-quay",
      "marina-bay"
    ]
  },
  {
    "slug": "osaka",
    "name": "Osaka",
    "countryCode": "JP",
    "center": {
      "lat": 34.6937,
      "lng": 135.5023
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "dotonbori",
      "shinsaibashi",
      "umeda",
      "namba",
      "shinsekai",
      "tennoji",
      "nakazakicho",
      "amemura"
    ]
  },
  {
    "slug": "kyoto",
    "name": "Kyoto",
    "countryCode": "JP",
    "center": {
      "lat": 35.0116,
      "lng": 135.7681
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "gion",
      "higashiyama",
      "arashiyama",
      "pontocho",
      "nishiki",
      "kiyamachi",
      "fushimi"
    ]
  },
  {
    "slug": "taipei",
    "name": "Taipei",
    "countryCode": "TW",
    "center": {
      "lat": 25.033,
      "lng": 121.5654
    },
    "timezone": "Asia/Taipei",
    "currency": "TWD",
    "languages": [
      "zh",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "ximending",
      "daan",
      "xinyi",
      "shilin",
      "wanhua",
      "zhongshan",
      "songshan",
      "yongkang-street"
    ]
  },
  {
    "slug": "hong-kong",
    "name": "Hong Kong",
    "countryCode": "HK",
    "center": {
      "lat": 22.3193,
      "lng": 114.1694
    },
    "timezone": "Asia/Hong_Kong",
    "currency": "HKD",
    "languages": [
      "zh",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "central",
      "sheung-wan",
      "wan-chai",
      "causeway-bay",
      "mong-kok",
      "tsim-sha-tsui",
      "sham-shui-po",
      "kennedy-town"
    ]
  },
  {
    "slug": "busan",
    "name": "Busan",
    "countryCode": "KR",
    "center": {
      "lat": 35.1796,
      "lng": 129.0756
    },
    "timezone": "Asia/Seoul",
    "currency": "KRW",
    "languages": [
      "ko",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "haeundae",
      "seomyeon",
      "nampo-dong",
      "gwangalli",
      "gamcheon",
      "jagalchi",
      "centum-city"
    ]
  },
  {
    "slug": "jeju",
    "name": "Jeju",
    "countryCode": "KR",
    "center": {
      "lat": 33.4996,
      "lng": 126.5312
    },
    "timezone": "Asia/Seoul",
    "currency": "KRW",
    "languages": [
      "ko",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "jeju-city",
      "seogwipo",
      "aewol",
      "hallim",
      "jungmun",
      "udo-island"
    ]
  },
  {
    "slug": "hanoi",
    "name": "Hanoi",
    "countryCode": "VN",
    "center": {
      "lat": 21.0278,
      "lng": 105.8342
    },
    "timezone": "Asia/Ho_Chi_Minh",
    "currency": "VND",
    "languages": [
      "vi",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "old-quarter",
      "hoan-kiem",
      "ba-dinh",
      "tay-ho",
      "dong-da",
      "sa-pa",
      "ninh-binh",
      "ha-long"
    ]
  },
  {
    "slug": "ho-chi-minh",
    "name": "Ho Chi Minh City",
    "countryCode": "VN",
    "center": {
      "lat": 10.8231,
      "lng": 106.6297
    },
    "timezone": "Asia/Ho_Chi_Minh",
    "currency": "VND",
    "languages": [
      "vi",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "district-1",
      "district-3",
      "district-7",
      "binh-thanh",
      "phu-nhuan",
      "thu-duc"
    ]
  },
  {
    "slug": "kuala-lumpur",
    "name": "Kuala Lumpur",
    "countryCode": "MY",
    "center": {
      "lat": 3.139,
      "lng": 101.6869
    },
    "timezone": "Asia/Kuala_Lumpur",
    "currency": "MYR",
    "languages": [
      "ms",
      "en",
      "zh"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "bukit-bintang",
      "klcc",
      "bangsar",
      "mont-kiara",
      "petaling-jaya",
      "chow-kit",
      "chinatown",
      "melaka"
    ]
  },
  {
    "slug": "bali-ubud",
    "name": "Ubud, Bali",
    "countryCode": "ID",
    "center": {
      "lat": -8.5069,
      "lng": 115.2625
    },
    "timezone": "Asia/Makassar",
    "currency": "IDR",
    "languages": [
      "id",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "central-ubud",
      "tegallalang",
      "penestanan",
      "campuhan",
      "mas",
      "peliatan"
    ]
  },
  {
    "slug": "bali-canggu",
    "name": "Canggu, Bali",
    "countryCode": "ID",
    "center": {
      "lat": -8.6478,
      "lng": 115.1385
    },
    "timezone": "Asia/Makassar",
    "currency": "IDR",
    "languages": [
      "id",
      "en"
    ],
    "ring": 2,
    "isEnabled": true,
    "localAreaSlugs": [
      "batu-bolong",
      "berawa",
      "echo-beach",
      "pererenan",
      "seseh"
    ]
  },
  {
    "slug": "chiang-mai",
    "name": "Chiang Mai",
    "countryCode": "TH",
    "center": {
      "lat": 18.7883,
      "lng": 98.9853
    },
    "timezone": "Asia/Bangkok",
    "currency": "THB",
    "languages": [
      "th",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "old-city",
      "nimmanhaemin",
      "santitham",
      "night-bazaar",
      "riverside"
    ]
  },
  {
    "slug": "keelung",
    "name": "Keelung",
    "countryCode": "TW",
    "center": {
      "lat": 25.1276,
      "lng": 121.7392
    },
    "timezone": "Asia/Taipei",
    "currency": "TWD",
    "languages": [
      "zh",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "zhongzheng",
      "renai",
      "miaokou",
      "badouzi",
      "heping-island"
    ]
  },
  {
    "slug": "yilan",
    "name": "Yilan",
    "countryCode": "TW",
    "center": {
      "lat": 24.7021,
      "lng": 121.7378
    },
    "timezone": "Asia/Taipei",
    "currency": "TWD",
    "languages": [
      "zh",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "yilan-city",
      "luodong",
      "jiaoxi",
      "wujie",
      "dongshan"
    ]
  },
  {
    "slug": "da-nang",
    "name": "Da Nang",
    "countryCode": "VN",
    "center": {
      "lat": 16.0544,
      "lng": 108.2022
    },
    "timezone": "Asia/Ho_Chi_Minh",
    "currency": "VND",
    "languages": [
      "vi",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "my-khe-beach",
      "han-river",
      "son-tra",
      "hoi-an"
    ]
  },
  {
    "slug": "penang",
    "name": "Penang",
    "countryCode": "MY",
    "center": {
      "lat": 5.4164,
      "lng": 100.3327
    },
    "timezone": "Asia/Kuala_Lumpur",
    "currency": "MYR",
    "languages": [
      "ms",
      "en",
      "zh"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "george-town",
      "gurney-drive",
      "batu-ferringhi",
      "air-itam"
    ]
  },
  {
    "slug": "nara",
    "name": "Nara",
    "countryCode": "JP",
    "center": {
      "lat": 34.6851,
      "lng": 135.8048
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "nara-park",
      "naramachi",
      "todai-ji-area",
      "kasuga-area"
    ]
  },
  {
    "slug": "kanazawa",
    "name": "Kanazawa",
    "countryCode": "JP",
    "center": {
      "lat": 36.5613,
      "lng": 136.6562
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "kenrokuen",
      "higashi-chaya",
      "kazuemachi",
      "nagamachi"
    ]
  },
  {
    "slug": "gyeongju",
    "name": "Gyeongju",
    "countryCode": "KR",
    "center": {
      "lat": 35.8562,
      "lng": 129.2247
    },
    "timezone": "Asia/Seoul",
    "currency": "KRW",
    "languages": [
      "ko",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "downtown",
      "bomun-lake",
      "bulguksa-area",
      "yangdong-village"
    ]
  },
  {
    "slug": "sapporo",
    "name": "Sapporo",
    "countryCode": "JP",
    "center": {
      "lat": 43.0618,
      "lng": 141.3545
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "susukino",
      "odori",
      "tanukikoji",
      "maruyama"
    ]
  },
  {
    "slug": "okinawa",
    "name": "Okinawa",
    "countryCode": "JP",
    "center": {
      "lat": 26.3344,
      "lng": 127.8056
    },
    "timezone": "Asia/Tokyo",
    "currency": "JPY",
    "languages": [
      "ja",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "naha",
      "kokusai-street",
      "shuri",
      "chatan",
      "nago"
    ]
  },
  {
    "slug": "manila",
    "name": "Manila",
    "countryCode": "PH",
    "center": {
      "lat": 14.5995,
      "lng": 120.9842
    },
    "timezone": "Asia/Manila",
    "currency": "PHP",
    "languages": [
      "tl",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "makati",
      "bgc",
      "intramuros",
      "binondo",
      "poblacion",
      "quezon-city",
      "escolta",
      "maginhawa"
    ]
  },
  {
    "slug": "phuket",
    "name": "Phuket",
    "countryCode": "TH",
    "center": {
      "lat": 7.8804,
      "lng": 98.3923
    },
    "timezone": "Asia/Bangkok",
    "currency": "THB",
    "languages": [
      "th",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "old-town",
      "patong",
      "kata",
      "karon",
      "rawai",
      "kamala",
      "surin",
      "bang-tao"
    ]
  },
  {
    "slug": "siem-reap",
    "name": "Siem Reap",
    "countryCode": "KH",
    "center": {
      "lat": 13.3671,
      "lng": 103.8448
    },
    "timezone": "Asia/Phnom_Penh",
    "currency": "KHR",
    "languages": [
      "km",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "old-market",
      "pub-street",
      "wat-bo",
      "sivatha",
      "charles-de-gaulle",
      "angkor-area"
    ]
  },
  {
    "slug": "hoi-an",
    "name": "Hoi An",
    "countryCode": "VN",
    "center": {
      "lat": 15.8801,
      "lng": 108.338
    },
    "timezone": "Asia/Ho_Chi_Minh",
    "currency": "VND",
    "languages": [
      "vi",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "ancient-town",
      "an-bang-beach",
      "cam-nam",
      "tra-que",
      "cua-dai",
      "an-hoi"
    ]
  },
  {
    "slug": "luang-prabang",
    "name": "Luang Prabang",
    "countryCode": "LA",
    "center": {
      "lat": 19.8857,
      "lng": 102.1347
    },
    "timezone": "Asia/Vientiane",
    "currency": "LAK",
    "languages": [
      "lo",
      "en"
    ],
    "ring": 3,
    "isEnabled": true,
    "localAreaSlugs": [
      "old-town",
      "mekong-riverside",
      "night-market",
      "phousi-hill",
      "ban-xang-khong",
      "xieng-thong"
    ]
  }
] as const;

export type GeneratedDestination = (typeof GENERATED_DESTINATIONS)[number];
