import { createHash } from "node:crypto";
import { normalizeGeoAlias, type GeographyManifest } from "./manifest-schema";

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonicalize);
  if (!value || typeof value !== "object") return value;
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, child]) => [key, canonicalize(child)]),
  );
}

export function getGeographyManifestFingerprint(manifest: GeographyManifest): string {
  return createHash("sha256")
    .update(JSON.stringify(canonicalize(manifest)))
    .digest("hex");
}

export function getGeographySeedSummary(manifest: GeographyManifest) {
  const corridorDestinations = manifest.destinations.filter((destination) =>
    ["KR", "JP"].includes(destination.countryCode),
  );
  return {
    version: manifest.version,
    countries: manifest.countries.length,
    destinations: manifest.destinations.length,
    localAreas: manifest.destinations.reduce(
      (total, destination) => total + destination.localAreas.length,
      0,
    ),
    corridorDestinations: corridorDestinations.length,
    corridorLocalAreas: corridorDestinations.reduce(
      (total, destination) => total + destination.localAreas.length,
      0,
    ),
    vibeAxes: manifest.vibeTaxonomy.length,
    fingerprint: getGeographyManifestFingerprint(manifest),
  };
}

export function buildCountrySeedRows(manifest: GeographyManifest) {
  return manifest.countries.map((country) => ({
    code: country.code,
    name: country.name,
    default_currency: country.defaultCurrency,
    default_languages: country.defaultLanguages,
    source_meta: country.sourceMeta,
    updated_at: manifest.reviewedAt,
  }));
}

export function buildDestinationSeedRows(manifest: GeographyManifest) {
  return manifest.destinations.map((destination) => ({
    slug: destination.slug,
    name: destination.name,
    country_code: destination.countryCode,
    center: `POINT(${destination.center.lng} ${destination.center.lat})`,
    timezone: destination.timezone,
    currency: destination.currency,
    languages: destination.languages,
    ring: destination.ring,
    is_enabled: destination.isEnabled,
    targets: destination.targets,
    characterization: destination.characterization,
    source_meta: destination.sourceMeta,
    reviewed_at: destination.reviewedAt,
    updated_at: manifest.reviewedAt,
  }));
}

export function buildVibeTaxonomySeedRows(manifest: GeographyManifest) {
  return manifest.vibeTaxonomy.map((vibe) => ({
    slug: vibe.slug,
    label: vibe.label,
    version: vibe.version,
    rubric: vibe.rubric,
  }));
}

export function buildTypedSnapshotSource(manifest: GeographyManifest): string {
  const fingerprint = getGeographyManifestFingerprint(manifest);
  const destinations = manifest.destinations.map((destination) => ({
    slug: destination.slug,
    name: destination.name.en,
    countryCode: destination.countryCode,
    center: destination.center,
    timezone: destination.timezone,
    currency: destination.currency,
    languages: destination.languages,
    ring: destination.ring,
    isEnabled: destination.isEnabled,
    localAreaSlugs: destination.localAreas.map((area) => area.slug),
  }));
  return `// Generated by scripts/generate-geography-snapshot.ts. Do not edit manually.\n` +
    `export const GEOGRAPHY_MANIFEST_FINGERPRINT = ${JSON.stringify(fingerprint)} as const;\n\n` +
    `export const GENERATED_DESTINATIONS = ${JSON.stringify(destinations, null, 2)} as const;\n\n` +
    `export type GeneratedDestination = (typeof GENERATED_DESTINATIONS)[number];\n`;
}

export function destinationAliasRows(input: {
  destinationId: string;
  aliases: string[];
  source: string;
}) {
  return input.aliases.map((alias) => ({
    entity_type: "destination" as const,
    destination_id: input.destinationId,
    local_area_id: null,
    spot_id: null,
    alias,
    normalized_alias: normalizeGeoAlias(alias),
    lang: null,
    source: input.source,
  }));
}

export function localAreaAliasRows(input: {
  localAreaId: string;
  canonicalName: string;
  aliases: string[];
  source: string;
}) {
  return [input.canonicalName, ...input.aliases].map((alias) => ({
    entity_type: "local_area" as const,
    destination_id: null,
    local_area_id: input.localAreaId,
    spot_id: null,
    alias,
    normalized_alias: normalizeGeoAlias(alias),
    lang: null,
    source: input.source,
  }));
}
