/**
 * Cloudflare Workers entry for the OpenNext build of the Next.js app.
 *
 * `fetch` is the generated OpenNext handler. `scheduled` replaces Vercel Cron:
 * each Cron Trigger calls its existing `/api/cron/*` route through the
 * WORKER_SELF_REFERENCE service binding with the CRON_SECRET bearer token.
 */
// Generated by `opennextjs-cloudflare build`; absent before the first build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as handler } from "../../.open-next/worker.js";
import { runScheduledRoute, type ScheduledController, type ScheduledEnv } from "./cron-routes";

interface WorkerExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
}

const worker = {
  fetch: handler.fetch,
  async scheduled(controller: ScheduledController, env: ScheduledEnv, ctx: WorkerExecutionContext) {
    ctx.waitUntil(runScheduledRoute(controller, env));
  },
};

export default worker;
