-- Seed Spots SQL
-- Run this in Supabase Dashboard > SQL Editor
-- This will insert 20 spots across Seoul, Tokyo, Bangkok, and Singapore

-- First, clear existing spots (optional - uncomment if you want to start fresh)
-- DELETE FROM spots;

INSERT INTO spots (name, description, location, address, category, subcategories, localley_score, local_percentage, best_times, photos, tips, verified, trending_score)
VALUES
-- Seoul, South Korea
(
    '{"en": "Mangwon Market Street Food Alley", "ko": "망원시장 먹자골목"}'::jsonb,
    '{"en": "Hidden food alley in Mangwon Market where locals grab authentic Korean street food. No tourists, just pure Seoul vibes.", "ko": "망원시장 안 숨겨진 먹자골목. 관광객 없이 순수한 서울 분위기."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9024, 37.5558), 4326)::geography,
    '{"en": "Mangwon-dong, Mapo-gu, Seoul", "ko": "서울 마포구 망원동"}'::jsonb,
    'Food',
    ARRAY['Street Food', 'Korean', 'Market'],
    5,
    95,
    '{"en": "Weekday evenings 6-8 PM", "ko": "평일 저녁 6-8시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800'],
    '{"en": ["Cash only", "Try the tteokbokki from the corner stall", "Go hungry - portions are huge"]}'::jsonb,
    true,
    0.3
),
(
    '{"en": "Seongsu Cafe Street", "ko": "성수동 카페거리"}'::jsonb,
    '{"en": "Industrial-chic neighborhood turned hipster cafe haven. Former factories now house Seoul''s coolest coffee shops.", "ko": "공장지대에서 힙스터 카페 천국으로 변신한 동네."}'::jsonb,
    ST_SetSRID(ST_MakePoint(127.0557, 37.5443), 4326)::geography,
    '{"en": "Seongsu-dong, Seongdong-gu, Seoul", "ko": "서울 성동구 성수동"}'::jsonb,
    'Cafe',
    ARRAY['Coffee', 'Dessert', 'Instagram-worthy'],
    4,
    70,
    '{"en": "Weekend afternoons 2-5 PM", "ko": "주말 오후 2-5시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
    '{"en": ["Explore the side alleys", "Most cafes open after 11 AM", "Parking is difficult - take subway"]}'::jsonb,
    true,
    0.85
),
(
    '{"en": "Ikseon-dong Hanok Village", "ko": "익선동 한옥마을"}'::jsonb,
    '{"en": "Traditional Korean houses converted into trendy bars and restaurants. Less touristy than Bukchon, more authentic vibes.", "ko": "전통 한옥을 개조한 트렌디한 바와 레스토랑. 북촌보다 덜 관광지화됨."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9916, 37.5714), 4326)::geography,
    '{"en": "Ikseon-dong, Jongno-gu, Seoul", "ko": "서울 종로구 익선동"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Korean Fusion', 'Historic'],
    4,
    65,
    '{"en": "Weeknight evenings 7-10 PM", "ko": "평일 저녁 7-10시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1583470790878-4e0a76e0e5c5?w=800'],
    '{"en": ["Narrow alleys - easy to get lost", "Reservations recommended for dinner", "Cash-friendly"]}'::jsonb,
    true,
    0.75
),
(
    '{"en": "Gwangjang Market Bindaetteok Alley", "ko": "광장시장 빈대떡 골목"}'::jsonb,
    '{"en": "The OG Korean pancake spot. Locals have been coming here for 100+ years. Sit at the counter and watch the magic happen.", "ko": "100년 넘게 이어온 빈대떡 명소. 카운터에 앉아 요리 과정을 구경하세요."}'::jsonb,
    ST_SetSRID(ST_MakePoint(127.0099, 37.5701), 4326)::geography,
    '{"en": "Jongno 4-ga, Jongno-gu, Seoul", "ko": "서울 종로구 종로4가"}'::jsonb,
    'Food',
    ARRAY['Korean', 'Market', 'Traditional'],
    6,
    90,
    '{"en": "Lunch time 12-2 PM", "ko": "점심시간 12-2시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800'],
    '{"en": ["Order bindaetteok (mung bean pancake)", "Pair with makgeolli (rice wine)", "Cash only, no English menu"]}'::jsonb,
    true,
    0.4
),
(
    '{"en": "Yeonnam-dong Gyeongui Line Forest", "ko": "연남동 경의선숲길"}'::jsonb,
    '{"en": "Former railway turned linear park with hidden cafes and boutiques along the path. Local''s favorite weekend stroll.", "ko": "옛 철길을 공원으로 만든 곳. 숨겨진 카페와 부티크가 즐비."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9246, 37.5641), 4326)::geography,
    '{"en": "Yeonnam-dong, Mapo-gu, Seoul", "ko": "서울 마포구 연남동"}'::jsonb,
    'Outdoor',
    ARRAY['Park', 'Shopping', 'Cafe'],
    5,
    80,
    '{"en": "Spring/Fall afternoons", "ko": "봄/가을 오후"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800'],
    '{"en": ["Rent a bike", "Check out the vintage shops", "Great for photos"]}'::jsonb,
    true,
    0.6
),

-- Tokyo, Japan
(
    '{"en": "Omoide Yokocho (Memory Lane)", "ja": "思い出横丁"}'::jsonb,
    '{"en": "Tiny yakitori alleys near Shinjuku Station. Smoky, cramped, and absolutely authentic. Where salarymen unwind after work.", "ja": "新宿駅近くの小さな焼き鳥横丁。煙たくて狭いけど本物の雰囲気。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7005, 35.6938), 4326)::geography,
    '{"en": "Nishi-Shinjuku, Shinjuku-ku, Tokyo", "ja": "東京都新宿区西新宿"}'::jsonb,
    'Food',
    ARRAY['Yakitori', 'Izakaya', 'Japanese'],
    5,
    85,
    '{"en": "Weeknight evenings 7-9 PM", "ja": "平日夜7-9時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800'],
    '{"en": ["Very small spaces - not for claustrophobics", "Cash only", "Order the chicken skin skewers"]}'::jsonb,
    true,
    0.5
),
(
    '{"en": "Shimokitazawa Vintage District", "ja": "下北沢古着街"}'::jsonb,
    '{"en": "Tokyo''s coolest neighborhood for vintage fashion and indie culture. Maze of narrow streets filled with thrift shops and live music venues.", "ja": "東京で一番クールな古着とインディーカルチャーの街。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.6681, 35.6617), 4326)::geography,
    '{"en": "Kitazawa, Setagaya-ku, Tokyo", "ja": "東京都世田谷区北沢"}'::jsonb,
    'Shopping',
    ARRAY['Vintage', 'Fashion', 'Music'],
    5,
    75,
    '{"en": "Weekend afternoons", "ja": "週末午後"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=800'],
    '{"en": ["Bargaining is acceptable", "Check out the basement shops", "Live music on weekends"]}'::jsonb,
    true,
    0.7
),
(
    '{"en": "Tsukiji Outer Market", "ja": "築地場外市場"}'::jsonb,
    '{"en": "The real deal for fresh sushi and seafood. Skip the tourist traps, eat where the chefs eat.", "ja": "本物の寿司と海鮮が食べられる場所。シェフが通う店で食べよう。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7709, 35.6654), 4326)::geography,
    '{"en": "Tsukiji, Chuo-ku, Tokyo", "ja": "東京都中央区築地"}'::jsonb,
    'Food',
    ARRAY['Sushi', 'Seafood', 'Market'],
    4,
    60,
    '{"en": "Early morning 6-9 AM", "ja": "早朝6-9時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800'],
    '{"en": ["Go early for best selection", "Cash only at most stalls", "Try the tamago (egg) sushi"]}'::jsonb,
    true,
    0.65
),
(
    '{"en": "Nakameguro River Walk", "ja": "中目黒川沿い"}'::jsonb,
    '{"en": "Cherry blossom paradise in spring, trendy cafes year-round. Less crowded than other sakura spots.", "ja": "春は桜の名所、年中トレンディなカフェが並ぶ。他の桜スポットより空いている。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.6983, 35.6436), 4326)::geography,
    '{"en": "Kamimeguro, Meguro-ku, Tokyo", "ja": "東京都目黒区上目黒"}'::jsonb,
    'Outdoor',
    ARRAY['Cherry Blossoms', 'Cafe', 'River'],
    4,
    70,
    '{"en": "Cherry blossom season (late March)", "ja": "桜の季節（3月下旬）"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800'],
    '{"en": ["Visit on weekdays to avoid crowds", "Evening illumination during sakura season", "Explore the side streets"]}'::jsonb,
    true,
    0.8
),
(
    '{"en": "Koenji Awa Odori Festival Street", "ja": "高円寺阿波踊り通り"}'::jsonb,
    '{"en": "Bohemian neighborhood with vintage shops, punk rock bars, and the best ramen you''ve never heard of.", "ja": "ビンテージショップ、パンクロックバー、知られざる最高のラーメン店がある。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.6493, 35.7058), 4326)::geography,
    '{"en": "Koenji-kita, Suginami-ku, Tokyo", "ja": "東京都杉並区高円寺北"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Ramen', 'Alternative'],
    6,
    95,
    '{"en": "Late night 10 PM-2 AM", "ja": "深夜10時-2時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800'],
    '{"en": ["Ramen shops open late", "Dive bars with no English signs", "Festival in late August"]}'::jsonb,
    true,
    0.35
),

-- Bangkok, Thailand
(
    '{"en": "Talad Rot Fai Ratchada", "th": "ตลาดนัดรถไฟรัชดา"}'::jsonb,
    '{"en": "Night market where Bangkok locals actually shop. Vintage finds, street food, and live music. Skip Chatuchak, come here.", "th": "คนกรุงเทพช็อปจริง ของวินเทจ อาหารริมทาง ดนตรีสด"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5608, 13.7613), 4326)::geography,
    '{"en": "Ratchadaphisek Rd, Din Daeng, Bangkok", "th": "ถ.รัชดาภิเษก ดินแดง กรุงเทพฯ"}'::jsonb,
    'Shopping',
    ARRAY['Night Market', 'Vintage', 'Street Food'],
    5,
    80,
    '{"en": "Thursday-Sunday evenings 5-11 PM", "th": "พฤ-อา เย็น 17-23น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800'],
    '{"en": ["Take MRT to Thailand Cultural Centre", "Bargain hard", "Try the grilled seafood"]}'::jsonb,
    true,
    0.6
),
(
    '{"en": "Ari Hipster District", "th": "ย่านอารีย์"}'::jsonb,
    '{"en": "Bangkok''s Brooklyn. Indie cafes, craft beer bars, and the best pad thai you''ll ever have. Zero tourists.", "th": "บรู๊คลินของกรุงเทพ คาเฟ่อินดี้ บาร์เบียร์คราฟต์ ผัดไทยเด็ด"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5411, 13.7792), 4326)::geography,
    '{"en": "Phahonyothin Rd, Phaya Thai, Bangkok", "th": "ถ.พหลโยธิน พญาไท กรุงเทพฯ"}'::jsonb,
    'Cafe',
    ARRAY['Coffee', 'Craft Beer', 'Thai Food'],
    5,
    90,
    '{"en": "Weekend brunch 10 AM-2 PM", "th": "สุดสัปดาห์ บรันช์ 10-14น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
    '{"en": ["Explore the sois (side streets)", "Parking is nightmare - take BTS", "Cash preferred"]}'::jsonb,
    true,
    0.75
),
(
    '{"en": "Yaowarat (Chinatown) Street Food", "th": "เยาวราช"}'::jsonb,
    '{"en": "The real Bangkok emerges at night. Neon-lit streets, smoking woks, and food that''ll change your life. Bring your appetite.", "th": "กรุงเทพที่แท้จริงตอนกลางคืน ถนนไฟนีออน กระทะควัน อาหารเปลี่ยนชีวิต"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5093, 13.7398), 4326)::geography,
    '{"en": "Yaowarat Rd, Samphanthawong, Bangkok", "th": "ถ.เยาวราช สัมพันธวงศ์ กรุงเทพฯ"}'::jsonb,
    'Food',
    ARRAY['Street Food', 'Chinese-Thai', 'Night Market'],
    6,
    85,
    '{"en": "Night time 7-11 PM", "th": "กลางคืน 19-23น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800'],
    '{"en": ["Wear comfortable shoes", "Try the crab omelet", "Cash only, small bills"]}'::jsonb,
    true,
    0.45
),
(
    '{"en": "Thonglor Soi 11 Bar Alley", "th": "ซอยทองหล่อ 11"}'::jsonb,
    '{"en": "Where Bangkok''s cool kids drink. Speakeasies, rooftop bars, and craft cocktails. Dress code: effortlessly cool.", "th": "ที่คนเท่กรุงเทพดื่ม บาร์ลับ รูฟท็อป ค็อกเทลคราฟต์"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5725, 13.7364), 4326)::geography,
    '{"en": "Thonglor Soi 11, Watthana, Bangkok", "th": "ทองหล่อ ซอย 11 วัฒนา กรุงเทพฯ"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Cocktails', 'Rooftop'],
    4,
    70,
    '{"en": "Friday-Saturday nights 9 PM-1 AM", "th": "ศุกร์-เสาร์ คืน 21-01น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800'],
    '{"en": ["Reservations recommended", "Dress smart-casual", "Expensive but worth it"]}'::jsonb,
    true,
    0.8
),
(
    '{"en": "Khlong Lat Mayom Floating Market", "th": "ตลาดน้ำคลองลัดมะยม"}'::jsonb,
    '{"en": "The floating market locals actually use. No elephant pants, just fresh produce and grandma''s recipes.", "th": "ตลาดน้ำที่คนท้องถิ่นใช้จริง ไม่มีกางเกงช้าง แค่ผักสดและสูตรยาย"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.4125, 13.7833), 4326)::geography,
    '{"en": "Bang Ramat, Taling Chan, Bangkok", "th": "บางระมาด ตลิ่งชัน กรุงเทพฯ"}'::jsonb,
    'Market',
    ARRAY['Floating Market', 'Thai Food', 'Traditional'],
    6,
    95,
    '{"en": "Saturday-Sunday mornings 8-11 AM", "th": "เสาร์-อา เช้า 8-11น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800'],
    '{"en": ["Take a boat tour", "Try the boat noodles", "Wear sunscreen"]}'::jsonb,
    true,
    0.3
),

-- Singapore
(
    '{"en": "Tiong Bahru Estate", "zh": "中峇鲁"}'::jsonb,
    '{"en": "Singapore''s hippest hood. Art Deco architecture meets indie bookstores and artisanal bakeries. Where cool Singaporeans brunch.", "zh": "新加坡最潮的社区。装饰艺术建筑遇上独立书店和手工面包店。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8270, 1.2862), 4326)::geography,
    '{"en": "Tiong Bahru, Singapore", "zh": "中峇鲁，新加坡"}'::jsonb,
    'Cafe',
    ARRAY['Coffee', 'Bakery', 'Books'],
    5,
    75,
    '{"en": "Weekend mornings 9-12 PM", "zh": "周末早上9-12点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=800'],
    '{"en": ["Visit the wet market first", "Books Actually is a must-visit", "Try the kaya toast"]}'::jsonb,
    true,
    0.7
),
(
    '{"en": "Jalan Besar Hipster Enclave", "zh": "惹兰勿刹"}'::jsonb,
    '{"en": "Old-school shophouses turned trendy cafes and bars. Singapore''s answer to gentrification done right.", "zh": "老店屋变身时尚咖啡馆和酒吧。新加坡的绅士化典范。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8565, 1.3058), 4326)::geography,
    '{"en": "Jalan Besar, Singapore", "zh": "惹兰勿刹，新加坡"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Cafe', 'Heritage'],
    5,
    80,
    '{"en": "Weeknight evenings 6-10 PM", "zh": "平日晚上6-10点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    '{"en": ["Explore the side lanes", "Mix of old and new", "Great for photos"]}'::jsonb,
    true,
    0.65
),
(
    '{"en": "Tekka Centre Hawker", "zh": "竹脚中心"}'::jsonb,
    '{"en": "Little India''s food court. Authentic Indian cuisine at hawker prices. Where the Indian community eats.", "zh": "小印度的美食中心。正宗印度菜，小贩价格。印度社区吃饭的地方。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8517, 1.3063), 4326)::geography,
    '{"en": "Serangoon Rd, Little India, Singapore", "zh": "实龙岗路，小印度，新加坡"}'::jsonb,
    'Food',
    ARRAY['Indian', 'Hawker', 'Halal'],
    6,
    90,
    '{"en": "Lunch time 12-2 PM", "zh": "午餐时间12-2点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800'],
    '{"en": ["Try the biryani", "Cash only", "Go hungry"]}'::jsonb,
    true,
    0.4
),
(
    '{"en": "Haji Lane", "zh": "哈芝巷"}'::jsonb,
    '{"en": "Narrow street packed with boutiques, street art, and Middle Eastern cafes. Instagram heaven, but still authentic.", "zh": "狭窄街道挤满精品店、街头艺术和中东咖啡馆。Instagram天堂，但仍然真实。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8589, 1.3008), 4326)::geography,
    '{"en": "Haji Lane, Kampong Glam, Singapore", "zh": "哈芝巷，甘榜格南，新加坡"}'::jsonb,
    'Shopping',
    ARRAY['Boutique', 'Street Art', 'Cafe'],
    3,
    50,
    '{"en": "Afternoon 2-6 PM", "zh": "下午2-6点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800'],
    '{"en": ["Weekdays less crowded", "Explore Arab Street nearby", "Bring camera"]}'::jsonb,
    true,
    0.9
),
(
    '{"en": "East Coast Lagoon Food Village", "zh": "东海岸泻湖美食村"}'::jsonb,
    '{"en": "Beachside hawker centre where Singaporeans go for weekend seafood feasts. Sunset views included.", "zh": "海滨小贩中心，新加坡人周末海鲜盛宴的地方。包括日落美景。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.9295, 1.3008), 4326)::geography,
    '{"en": "East Coast Park, Singapore", "zh": "东海岸公园，新加坡"}'::jsonb,
    'Food',
    ARRAY['Seafood', 'Hawker', 'Beachside'],
    5,
    85,
    '{"en": "Weekend evenings 5-8 PM", "zh": "周末晚上5-8点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
    '{"en": ["Try the BBQ stingray", "Bring mosquito repellent", "Parking fills up fast"]}'::jsonb,
    true,
    0.5
);

-- Verify the insert
SELECT COUNT(*) as total_spots FROM spots;
SELECT name->>'en' as spot_name, category, localley_score FROM spots ORDER BY localley_score DESC;
