-- Additional 30 Spots SQL
-- Run this in Supabase Dashboard > SQL Editor AFTER running seed-spots.sql
-- This adds 30 more spots (7 Seoul, 8 Tokyo, 8 Bangkok, 7 Singapore)

INSERT INTO spots (name, description, location, address, category, subcategories, localley_score, local_percentage, best_times, photos, tips, verified, trending_score)
VALUES
-- Seoul, South Korea (7 more spots)
(
    '{"en": "Bukchon Hanok Village", "ko": "북촌한옥마을"}'::jsonb,
    '{"en": "Traditional Korean houses in the heart of Seoul. Less touristy in early mornings, stunning architecture and quiet alleyways.", "ko": "서울 중심부의 전통 한옥. 이른 아침에는 관광객이 적고 조용함."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9850, 37.5825), 4326)::geography,
    '{"en": "Gahoe-dong, Jongno-gu, Seoul", "ko": "서울 종로구 가회동"}'::jsonb,
    'Outdoor',
    ARRAY['Historic', 'Architecture', 'Walking'],
    3,
    40,
    '{"en": "Early morning 6-8 AM", "ko": "이른 아침 6-8시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800'],
    '{"en": ["Visit early to avoid crowds", "Respect residents'' privacy", "Combine with nearby museums"]}'::jsonb,
    true,
    0.6
),
(
    '{"en": "Hongdae Playground Street", "ko": "홍대 놀이터거리"}'::jsonb,
    '{"en": "Street performances, indie music, and young energy. Where Seoul''s creative youth gather. Best on weekend evenings.", "ko": "거리 공연, 인디 음악, 젊은 에너지. 서울의 창의적인 젊은이들이 모이는 곳."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9227, 37.5563), 4326)::geography,
    '{"en": "Hongdae, Mapo-gu, Seoul", "ko": "서울 마포구 홍대"}'::jsonb,
    'Nightlife',
    ARRAY['Music', 'Street Performance', 'Youth Culture'],
    4,
    65,
    '{"en": "Friday-Saturday evenings 7-11 PM", "ko": "금-토 저녁 7-11시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800'],
    '{"en": ["Cash for street food", "Check out the indie clubs", "Busking starts around 7 PM"]}'::jsonb,
    true,
    0.75
),
(
    '{"en": "Namdaemun Market", "ko": "남대문시장"}'::jsonb,
    '{"en": "Korea''s oldest and largest market. Wholesale prices, authentic street food, and zero English. Pure Seoul chaos in the best way.", "ko": "한국에서 가장 오래되고 큰 시장. 도매가격, 진짜 길거리 음식."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9776, 37.5595), 4326)::geography,
    '{"en": "Namdaemun-ro, Jung-gu, Seoul", "ko": "서울 중구 남대문로"}'::jsonb,
    'Market',
    ARRAY['Shopping', 'Street Food', 'Wholesale'],
    5,
    85,
    '{"en": "Early morning 5-9 AM", "ko": "이른 아침 5-9시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800'],
    '{"en": ["Bargain hard", "Try the kalguksu (knife-cut noodles)", "Some shops close by afternoon"]}'::jsonb,
    true,
    0.4
),
(
    '{"en": "Garosu-gil", "ko": "가로수길"}'::jsonb,
    '{"en": "Tree-lined street with boutique shops and trendy cafes. Seoul''s fashion district with a European vibe.", "ko": "가로수가 늘어선 거리에 부티크 샵과 트렌디한 카페. 유럽 느낌."}'::jsonb,
    ST_SetSRID(ST_MakePoint(127.0226, 37.5194), 4326)::geography,
    '{"en": "Sinsa-dong, Gangnam-gu, Seoul", "ko": "서울 강남구 신사동"}'::jsonb,
    'Shopping',
    ARRAY['Fashion', 'Cafe', 'Boutique'],
    3,
    55,
    '{"en": "Weekday afternoons 2-6 PM", "ko": "평일 오후 2-6시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
    '{"en": ["Explore the side alleys", "Expensive but quality", "Great for people watching"]}'::jsonb,
    true,
    0.7
),
(
    '{"en": "Noryangjin Fish Market", "ko": "노량진수산시장"}'::jsonb,
    '{"en": "24-hour fish market where you can buy fresh seafood and have it prepared upstairs. Raw, real, and unforgettable.", "ko": "24시간 수산시장. 신선한 해산물을 사서 위층에서 바로 먹을 수 있음."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9423, 37.5133), 4326)::geography,
    '{"en": "Noryangjin-dong, Dongjak-gu, Seoul", "ko": "서울 동작구 노량진동"}'::jsonb,
    'Food',
    ARRAY['Seafood', 'Market', '24-Hour'],
    6,
    95,
    '{"en": "Late night 10 PM-2 AM or early morning", "ko": "늦은 밤 10시-새벽 2시 또는 이른 아침"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800'],
    '{"en": ["Bargain expected", "Bring cash", "Try the live octopus"]}'::jsonb,
    true,
    0.35
),
(
    '{"en": "Samcheong-dong Cafe Street", "ko": "삼청동 카페거리"}'::jsonb,
    '{"en": "Charming neighborhood with traditional hanoks converted into art galleries and cafes. Quieter alternative to Insadong.", "ko": "전통 한옥을 개조한 미술관과 카페. 인사동보다 조용한 대안."}'::jsonb,
    ST_SetSRID(ST_MakePoint(126.9825, 37.5825), 4326)::geography,
    '{"en": "Samcheong-dong, Jongno-gu, Seoul", "ko": "서울 종로구 삼청동"}'::jsonb,
    'Cafe',
    ARRAY['Art', 'Traditional', 'Coffee'],
    4,
    70,
    '{"en": "Weekday afternoons", "ko": "평일 오후"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
    '{"en": ["Visit the galleries", "Uphill walk from Gyeongbokgung", "Expensive but atmospheric"]}'::jsonb,
    true,
    0.65
),
(
    '{"en": "Dongdaemun Design Plaza (DDP) Night Market", "ko": "동대문디자인플라자 야시장"}'::jsonb,
    '{"en": "Futuristic architecture meets night market. Fashion, food, and late-night shopping until dawn.", "ko": "미래적인 건축물과 야시장. 패션, 음식, 새벽까지 쇼핑."}'::jsonb,
    ST_SetSRID(ST_MakePoint(127.0096, 37.5665), 4326)::geography,
    '{"en": "Euljiro, Jung-gu, Seoul", "ko": "서울 중구 을지로"}'::jsonb,
    'Shopping',
    ARRAY['Fashion', 'Night Market', 'Design'],
    3,
    50,
    '{"en": "Late night 10 PM-4 AM", "ko": "늦은 밤 10시-새벽 4시"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=800'],
    '{"en": ["Wholesale prices after midnight", "Bring cash", "Nearby Dongdaemun market is bigger"]}'::jsonb,
    true,
    0.8
),

-- Tokyo, Japan (8 more spots)
(
    '{"en": "Yanaka Ginza Shopping Street", "ja": "谷中銀座商店街"}'::jsonb,
    '{"en": "Old Tokyo vibes with traditional shops and street food. Survived WWII bombings, pure nostalgia.", "ja": "昔の東京の雰囲気。戦争を生き延びた商店街。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7653, 35.7275), 4326)::geography,
    '{"en": "Yanaka, Taito-ku, Tokyo", "ja": "東京都台東区谷中"}'::jsonb,
    'Shopping',
    ARRAY['Traditional', 'Street Food', 'Historic'],
    5,
    80,
    '{"en": "Afternoon 2-5 PM", "ja": "午後2-5時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=800'],
    '{"en": ["Try the menchi-katsu", "Visit nearby Yanaka Cemetery", "Closed Mondays"]}'::jsonb,
    true,
    0.55
),
(
    '{"en": "Daikanyama T-Site", "ja": "代官山蔦屋書店"}'::jsonb,
    '{"en": "Most beautiful bookstore in Tokyo. Design books, vinyl records, and a Starbucks that doesn''t feel corporate.", "ja": "東京で一番美しい本屋。デザイン本、レコード、おしゃれなスタバ。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7009, 35.6499), 4326)::geography,
    '{"en": "Sarugaku-cho, Shibuya-ku, Tokyo", "ja": "東京都渋谷区猿楽町"}'::jsonb,
    'Shopping',
    ARRAY['Books', 'Design', 'Cafe'],
    4,
    65,
    '{"en": "Weekday mornings", "ja": "平日午前"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800'],
    '{"en": ["English books available", "Lounge area on 2nd floor", "Pet-friendly"]}'::jsonb,
    true,
    0.7
),
(
    '{"en": "Kagurazaka French Quarter", "ja": "神楽坂フレンチ街"}'::jsonb,
    '{"en": "Tokyo''s Little Paris with cobblestone streets, French bistros, and geisha houses. Romantic and unexpected.", "ja": "東京の小さなパリ。石畳、フレンチビストロ、芸者の家。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7386, 35.7025), 4326)::geography,
    '{"en": "Kagurazaka, Shinjuku-ku, Tokyo", "ja": "東京都新宿区神楽坂"}'::jsonb,
    'Food',
    ARRAY['French', 'Romantic', 'Historic'],
    5,
    75,
    '{"en": "Evening 6-9 PM", "ja": "夕方6-9時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800'],
    '{"en": ["Reservations essential", "Explore the side alleys", "Expensive but worth it"]}'::jsonb,
    true,
    0.6
),
(
    '{"en": "Ameya-Yokocho Market", "ja": "アメヤ横丁"}'::jsonb,
    '{"en": "Post-war black market turned bustling bazaar. Cheap everything, loud vendors, pure Tokyo energy.", "ja": "戦後の闇市が賑やかな市場に。安い、うるさい、東京のエネルギー。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7745, 35.7125), 4326)::geography,
    '{"en": "Ueno, Taito-ku, Tokyo", "ja": "東京都台東区上野"}'::jsonb,
    'Market',
    ARRAY['Shopping', 'Street Food', 'Historic'],
    5,
    85,
    '{"en": "Afternoon 1-4 PM", "ja": "午後1-4時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800'],
    '{"en": ["Bargain expected", "Try the kebabs", "Cash only"]}'::jsonb,
    true,
    0.45
),
(
    '{"en": "Harmonica Yokocho", "ja": "ハモニカ横丁"}'::jsonb,
    '{"en": "Tiny alley of even tinier bars near Kichijoji. Squeeze in, drink cheap, make friends with salarymen.", "ja": "吉祥寺近くの小さなバーが並ぶ路地。狭い、安い、サラリーマンと友達に。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.5794, 35.7033), 4326)::geography,
    '{"en": "Kichijoji, Musashino, Tokyo", "ja": "東京都武蔵野市吉祥寺"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Izakaya', 'Local'],
    6,
    90,
    '{"en": "Late evening 8-11 PM", "ja": "夜8-11時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800'],
    '{"en": ["Cash only", "Most bars seat 6-8 people", "Order the yakitori"]}'::jsonb,
    true,
    0.4
),
(
    '{"en": "Yanesen Area", "ja": "谷根千エリア"}'::jsonb,
    '{"en": "Yanaka, Nezu, Sendagi combined. Old Tokyo preserved with temples, traditional shops, and cats everywhere.", "ja": "谷中、根津、千駄木。古い東京が保存されている。寺、伝統的な店、猫。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7653, 35.7275), 4326)::geography,
    '{"en": "Yanaka/Nezu/Sendagi, Taito-ku, Tokyo", "ja": "東京都台東区谷中・根津・千駄木"}'::jsonb,
    'Outdoor',
    ARRAY['Historic', 'Walking', 'Traditional'],
    5,
    80,
    '{"en": "Weekend mornings", "ja": "週末午前"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800'],
    '{"en": ["Wear comfortable shoes", "Visit the cat cafes", "Bring a camera"]}'::jsonb,
    true,
    0.5
),
(
    '{"en": "Daikoku-yu Sento", "ja": "大黒湯"}'::jsonb,
    '{"en": "Traditional public bathhouse with Mount Fuji mural. Experience real Tokyo bathing culture.", "ja": "富士山の壁画がある伝統的な銭湯。本物の東京の入浴文化。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7009, 35.6499), 4326)::geography,
    '{"en": "Meguro, Tokyo", "ja": "東京都目黒区"}'::jsonb,
    'Outdoor',
    ARRAY['Traditional', 'Wellness', 'Cultural'],
    6,
    95,
    '{"en": "Evening 6-9 PM", "ja": "夕方6-9時"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800'],
    '{"en": ["Bring your own towel", "No tattoos allowed", "¥500 entry"]}'::jsonb,
    true,
    0.3
),
(
    '{"en": "Kappabashi Kitchen Town", "ja": "かっぱ橋道具街"}'::jsonb,
    '{"en": "Where Tokyo chefs buy their tools. Knives, ceramics, and those plastic food displays. Unique shopping.", "ja": "東京のシェフが道具を買う場所。包丁、陶器、食品サンプル。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(139.7889, 35.7125), 4326)::geography,
    '{"en": "Matsugaya, Taito-ku, Tokyo", "ja": "東京都台東区松が谷"}'::jsonb,
    'Shopping',
    ARRAY['Kitchen', 'Professional', 'Unique'],
    5,
    75,
    '{"en": "Weekday afternoons", "ja": "平日午後"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=800'],
    '{"en": ["Tax-free shopping available", "Bring measurements", "Most shops close Sundays"]}'::jsonb,
    true,
    0.55
),

-- Bangkok, Thailand (8 more spots)
(
    '{"en": "Chatuchak Weekend Market", "th": "ตลาดนัดจตุจักร"}'::jsonb,
    '{"en": "World''s largest weekend market. 15,000 stalls, everything imaginable. Get lost, find treasures, repeat.", "th": "ตลาดนัดที่ใหญ่ที่สุดในโลก 15,000 ร้าน ทุกอย่างที่คิดได้"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5499, 13.7990), 4326)::geography,
    '{"en": "Chatuchak, Bangkok", "th": "จตุจักร กรุงเทพฯ"}'::jsonb,
    'Market',
    ARRAY['Shopping', 'Vintage', 'Food'],
    3,
    60,
    '{"en": "Saturday-Sunday mornings 9 AM-12 PM", "th": "เสาร์-อา เช้า 9-12น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800'],
    '{"en": ["Wear comfortable shoes", "Bring cash", "Go early to beat heat"]}'::jsonb,
    true,
    0.85
),
(
    '{"en": "Pak Khlong Talat Flower Market", "th": "ตลาดปากคลองตลาด"}'::jsonb,
    '{"en": "24-hour flower market. Best at 2-4 AM when fresh flowers arrive. Surreal and beautiful.", "th": "ตลาดดอกไม้ 24 ชั่วโมง ดีที่สุดตอนตี 2-4 เมื่อดอกไม้สดมาถึง"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.4928, 13.7439), 4326)::geography,
    '{"en": "Chakkrawat, Bangkok", "th": "จักรวรรดิ กรุงเทพฯ"}'::jsonb,
    'Market',
    ARRAY['Flowers', '24-Hour', 'Photography'],
    5,
    85,
    '{"en": "Late night 2-4 AM", "th": "ดึก 2-4น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800'],
    '{"en": ["Bring camera", "Watch for trucks", "Nearby temples beautiful at dawn"]}'::jsonb,
    true,
    0.5
),
(
    '{"en": "Soi Nana (Chinatown)", "th": "ซอยนานา เยาวราช"}'::jsonb,
    '{"en": "Hidden alley in Chinatown with the best street food. Locals only, no tourists, pure Bangkok.", "th": "ซอยลับในไชน่าทาวน์ อาหารริมทางที่ดีที่สุด คนท้องถิ่นเท่านั้น"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5093, 13.7398), 4326)::geography,
    '{"en": "Yaowarat, Bangkok", "th": "เยาวราช กรุงเทพฯ"}'::jsonb,
    'Food',
    ARRAY['Street Food', 'Chinese-Thai', 'Hidden'],
    6,
    95,
    '{"en": "Dinner time 6-9 PM", "th": "เย็น 6-9น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800'],
    '{"en": ["Cash only", "Point and order", "Try the crab curry"]}'::jsonb,
    true,
    0.3
),
(
    '{"en": "Warehouse 30", "th": "แวร์เฮ้าส์ 30"}'::jsonb,
    '{"en": "Converted warehouse with indie shops, cafes, and art spaces. Bangkok''s creative hub.", "th": "โกดังเก่าดัดแปลงเป็นร้านอินดี้ คาเฟ่ พื้นที่ศิลปะ"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5293, 13.7307), 4326)::geography,
    '{"en": "Charoen Krung, Bangkok", "th": "เจริญกรุง กรุงเทพฯ"}'::jsonb,
    'Shopping',
    ARRAY['Art', 'Indie', 'Cafe'],
    4,
    70,
    '{"en": "Weekend afternoons", "th": "สุดสัปดาห์ บ่าย"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800'],
    '{"en": ["Check event schedule", "Parking difficult", "Combine with Chinatown visit"]}'::jsonb,
    true,
    0.75
),
(
    '{"en": "Saphan Phut Night Market", "th": "ตลาดนัดสะพานพุทธ"}'::jsonb,
    '{"en": "Cheap fashion and street food by the river. Where Bangkok teens shop. Chaotic and fun.", "th": "แฟชั่นราคาถูกและอาหารริมแม่น้ำ วัยรุ่นกรุงเทพช็อป"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5028, 13.7439), 4326)::geography,
    '{"en": "Phra Nakhon, Bangkok", "th": "พระนคร กรุงเทพฯ"}'::jsonb,
    'Market',
    ARRAY['Fashion', 'Night Market', 'Youth'],
    5,
    80,
    '{"en": "Evening 6-10 PM", "th": "เย็น 6-10น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800'],
    '{"en": ["Bargain hard", "Cash only", "Watch for pickpockets"]}'::jsonb,
    true,
    0.6
),
(
    '{"en": "Phra Athit Road", "th": "ถนนพระอาทิตย์"}'::jsonb,
    '{"en": "Backpacker street turned hipster haven. Cheap beer, live music, and Chao Phraya river views.", "th": "ถนนแบ็คแพ็คเกอร์กลายเป็นสวรรค์ฮิปสเตอร์ เบียร์ถูก ดนตรีสด"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.4978, 13.7589), 4326)::geography,
    '{"en": "Phra Nakhon, Bangkok", "th": "พระนคร กรุงเทพฯ"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Live Music', 'River'],
    4,
    65,
    '{"en": "Evening 7-11 PM", "th": "เย็น 7-11น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800'],
    '{"en": ["Try the street food", "River ferry nearby", "Cheap drinks"]}'::jsonb,
    true,
    0.7
),
(
    '{"en": "Or Tor Kor Market", "th": "ตลาดอ.ต.ก."}'::jsonb,
    '{"en": "Bangkok''s best fresh market. Premium quality, clean, air-conditioned. Where locals buy the good stuff.", "th": "ตลาดสดที่ดีที่สุดในกรุงเทพ คุณภาพพรีเมียม สะอาด แอร์"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.5548, 13.8019), 4326)::geography,
    '{"en": "Chatuchak, Bangkok", "th": "จตุจักร กรุงเทพฯ"}'::jsonb,
    'Market',
    ARRAY['Food', 'Fresh Produce', 'Premium'],
    5,
    90,
    '{"en": "Morning 8-11 AM", "th": "เช้า 8-11น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800'],
    '{"en": ["Try the mango sticky rice", "Expensive but quality", "Food court upstairs"]}'::jsonb,
    true,
    0.55
),
(
    '{"en": "Soi Rambuttri", "th": "ซอยรามบุตรี"}'::jsonb,
    '{"en": "Quieter alternative to Khao San Road. Same vibe, fewer tourists, better prices.", "th": "ทางเลือกที่เงียบกว่าข้าวสาร บรรยากาศเดียวกัน นักท่องเที่ยวน้อยกว่า"}'::jsonb,
    ST_SetSRID(ST_MakePoint(100.4978, 13.7589), 4326)::geography,
    '{"en": "Phra Nakhon, Bangkok", "th": "พระนคร กรุงเทพฯ"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Backpacker', 'Budget'],
    4,
    60,
    '{"en": "Evening 7-12 PM", "th": "เย็น 7-12น."}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800'],
    '{"en": ["Cheaper than Khao San", "Good street food", "Quieter atmosphere"]}'::jsonb,
    true,
    0.5
),

-- Singapore (7 more spots)
(
    '{"en": "Katong/Joo Chiat", "zh": "加东/如切"}'::jsonb,
    '{"en": "Peranakan heritage district with colorful shophouses, laksa, and old-school charm. Real Singapore.", "zh": "娘惹文化区，彩色店屋，叻沙，老派魅力。真正的新加坡。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.9040, 1.3048), 4326)::geography,
    '{"en": "Katong, Singapore", "zh": "加东，新加坡"}'::jsonb,
    'Food',
    ARRAY['Peranakan', 'Heritage', 'Laksa'],
    5,
    80,
    '{"en": "Lunch time 11 AM-2 PM", "zh": "午餐时间11-14点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
    '{"en": ["Try 328 Katong Laksa", "Walk the heritage trail", "Colorful photo ops"]}'::jsonb,
    true,
    0.6
),
(
    '{"en": "Everton Park HDB Food Centre", "zh": "厄文顿公园组屋熟食中心"}'::jsonb,
    '{"en": "Local hawker centre where Singaporeans actually eat. No tourists, just good food and real prices.", "zh": "本地人真正吃饭的小贩中心。没有游客，只有好食物和真实价格。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8395, 1.2761), 4326)::geography,
    '{"en": "Everton Park, Singapore", "zh": "厄文顿公园，新加坡"}'::jsonb,
    'Food',
    ARRAY['Hawker', 'Local', 'Budget'],
    6,
    95,
    '{"en": "Breakfast 7-10 AM", "zh": "早餐7-10点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800'],
    '{"en": ["Try the char kway teow", "Cash only", "Go early"]}'::jsonb,
    true,
    0.3
),
(
    '{"en": "Kampong Glam", "zh": "甘榜格南"}'::jsonb,
    '{"en": "Malay-Arab quarter with Sultan Mosque, street art, and Middle Eastern cafes. Cultural melting pot.", "zh": "马来-阿拉伯区，苏丹清真寺，街头艺术，中东咖啡馆。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8589, 1.3008), 4326)::geography,
    '{"en": "Kampong Glam, Singapore", "zh": "甘榜格南，新加坡"}'::jsonb,
    'Outdoor',
    ARRAY['Heritage', 'Street Art', 'Cultural'],
    4,
    65,
    '{"en": "Afternoon 2-6 PM", "zh": "下午2-6点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800'],
    '{"en": ["Visit Sultan Mosque", "Try the Turkish food", "Haji Lane nearby"]}'::jsonb,
    true,
    0.75
),
(
    '{"en": "Geylang Serai Market", "zh": "芽笼士乃市场"}'::jsonb,
    '{"en": "Malay wet market and food centre. Authentic, bustling, and delicious. Where locals shop.", "zh": "马来湿巴刹和熟食中心。真实，热闹，美味。本地人购物的地方。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8989, 1.3158), 4326)::geography,
    '{"en": "Geylang Serai, Singapore", "zh": "芽笼士乃，新加坡"}'::jsonb,
    'Market',
    ARRAY['Wet Market', 'Malay', 'Food'],
    5,
    90,
    '{"en": "Morning 7-11 AM", "zh": "早上7-11点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800'],
    '{"en": ["Try the nasi padang", "Cash preferred", "Ramadan special during fasting month"]}'::jsonb,
    true,
    0.45
),
(
    '{"en": "Holland Village", "zh": "荷兰村"}'::jsonb,
    '{"en": "Expat enclave turned trendy dining spot. Mix of old-school and new cafes, bars, and restaurants.", "zh": "外籍人士聚集地变身时尚餐饮区。老派和新潮咖啡馆、酒吧、餐厅混合。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.7956, 1.3111), 4326)::geography,
    '{"en": "Holland Village, Singapore", "zh": "荷兰村，新加坡"}'::jsonb,
    'Nightlife',
    ARRAY['Bars', 'Dining', 'Expat'],
    3,
    50,
    '{"en": "Evening 6-10 PM", "zh": "晚上6-10点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800'],
    '{"en": ["Try the hawker centre", "Parking difficult", "Good for brunch"]}'::jsonb,
    true,
    0.65
),
(
    '{"en": "Pulau Ubin", "zh": "乌敏岛"}'::jsonb,
    '{"en": "Island escape from modern Singapore. Cycling, mangroves, and 1960s kampong vibes. Time travel.", "zh": "从现代新加坡逃离的岛屿。骑自行车，红树林，1960年代甘榜氛围。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.9608, 1.4044), 4326)::geography,
    '{"en": "Pulau Ubin, Singapore", "zh": "乌敏岛，新加坡"}'::jsonb,
    'Outdoor',
    ARRAY['Nature', 'Cycling', 'Island'],
    5,
    75,
    '{"en": "Weekend mornings", "zh": "周末早上"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800'],
    '{"en": ["Take bumboat from Changi", "Rent a bike", "Bring water and snacks"]}'::jsonb,
    true,
    0.5
),
(
    '{"en": "Chinatown Complex Food Centre", "zh": "牛车水大厦熟食中心"}'::jsonb,
    '{"en": "Legendary hawker centre with Michelin-starred stalls. Cheap, delicious, and always packed.", "zh": "传奇小贩中心，有米其林星级摊位。便宜，美味，总是挤满人。"}'::jsonb,
    ST_SetSRID(ST_MakePoint(103.8438, 1.2825), 4326)::geography,
    '{"en": "Chinatown, Singapore", "zh": "牛车水，新加坡"}'::jsonb,
    'Food',
    ARRAY['Hawker', 'Michelin', 'Chinese'],
    4,
    70,
    '{"en": "Lunch time 11 AM-2 PM", "zh": "午餐时间11-14点"}'::jsonb,
    ARRAY['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800'],
    '{"en": ["Try Liao Fan Hawker Chan", "Go early to avoid queues", "Cash only"]}'::jsonb,
    true,
    0.8
);

-- Verify the insert
SELECT COUNT(*) as total_spots FROM spots;
