PRAGMA foreign_keys = ON;
CREATE TABLE profiles (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36 AND id = lower(id) AND substr(id,9,1) = '-' AND substr(id,14,1) = '-' AND substr(id,19,1) = '-' AND substr(id,24,1) = '-' AND length(replace(id,'-','')) = 32 AND replace(id,'-','') NOT GLOB '*[^0-9a-f]*'), ownerId TEXT NOT NULL UNIQUE REFERENCES owners(id));
CREATE TABLE spots (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36 AND id = lower(id) AND substr(id,9,1) = '-' AND substr(id,14,1) = '-' AND substr(id,19,1) = '-' AND substr(id,24,1) = '-' AND length(replace(id,'-','')) = 32 AND replace(id,'-','') NOT GLOB '*[^0-9a-f]*'), name TEXT NOT NULL CHECK(json_valid(name) AND json_type(name) = 'object'), description TEXT NOT NULL CHECK(json_valid(description) AND json_type(description) = 'object'), category TEXT NOT NULL, localley_score INTEGER CHECK(localley_score IS NULL OR (typeof(localley_score) = 'integer' AND localley_score BETWEEN 1 AND 6)), photos TEXT CHECK(photos IS NULL OR (json_valid(photos) AND json_type(photos) = 'array')), visible INTEGER NOT NULL CHECK(visible IN (0,1)));
CREATE TABLE owner_limits (ownerId TEXT PRIMARY KEY NOT NULL REFERENCES owners(id), savedSpotLimit INTEGER NOT NULL CHECK(typeof(savedSpotLimit) = 'integer' AND savedSpotLimit BETWEEN 0 AND 999));
CREATE TABLE saved_spots (id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36 AND id = lower(id) AND substr(id,9,1) = '-' AND substr(id,14,1) = '-' AND substr(id,19,1) = '-' AND substr(id,24,1) = '-' AND length(replace(id,'-','')) = 32 AND replace(id,'-','') NOT GLOB '*[^0-9a-f]*'), ownerId TEXT NOT NULL REFERENCES owners(id), spotId TEXT NOT NULL CHECK(length(spotId) = 36 AND spotId = lower(spotId) AND substr(spotId,9,1) = '-' AND substr(spotId,14,1) = '-' AND substr(spotId,19,1) = '-' AND substr(spotId,24,1) = '-' AND length(replace(spotId,'-','')) = 32 AND replace(spotId,'-','') NOT GLOB '*[^0-9a-f]*'), createdAtMs INTEGER NOT NULL CHECK(typeof(createdAtMs) = 'integer' AND createdAtMs BETWEEN 0 AND 8640000000000000), UNIQUE(ownerId,spotId));
CREATE INDEX saved_spots_owner_order ON saved_spots(ownerId, createdAtMs DESC, id DESC);
CREATE INDEX saved_spots_spot ON saved_spots(spotId);
CREATE TABLE application_outbox (eventKey TEXT PRIMARY KEY NOT NULL, saveId TEXT NOT NULL, action TEXT NOT NULL CHECK(action = 'save'), ownerId TEXT NOT NULL REFERENCES owners(id), spotId TEXT NOT NULL, createdAt INTEGER NOT NULL CHECK(typeof(createdAt) = 'integer'), CHECK(eventKey = saveId || ':' || action));
CREATE INDEX application_outbox_created ON application_outbox(createdAt, eventKey);
