// Fixed source route templates; never persist values from dynamic or unknown paths.
const routes = [
  "/",
  "/admin/analytics",
  "/admin/spots/discovery",
  "/admin/spots/quality",
  "/admin/spots/social-submissions",
  "/api/admin/analytics",
  "/api/admin/guides",
  "/api/admin/llm-metrics",
  "/api/admin/payouts/approve",
  "/api/admin/payouts/calculate",
  "/api/admin/payouts/execute",
  "/api/admin/seed-spots",
  "/api/admin/spots/apify-discovery",
  "/api/admin/spots/backfill-location",
  "/api/admin/spots/backfill-photos",
  "/api/admin/spots/quality",
  "/api/admin/spots/social-submissions/backfill",
  "/api/affiliates/track",
  "/api/auth/[...all]",
  "/api/challenges",
  "/api/chat",
  "/api/cities",
  "/api/connect/dashboard",
  "/api/connect/earnings",
  "/api/connect/onboard",
  "/api/connect/status",
  "/api/connect/webhook",
  "/api/conversations",
  "/api/conversations/messages",
  "/api/cron/cleanup-stories",
  "/api/cron/discover-spots-with-apify",
  "/api/cron/process-social-submissions",
  "/api/cron/refresh-weekly-social-trends",
  "/api/debug/image-pipeline",
  "/api/early-adopter",
  "/api/friends",
  "/api/gamification/award",
  "/api/geocode",
  "/api/geocode/batch",
  "/api/images/generate",
  "/api/images/story-background",
  "/api/images/story-background/media/[id]",
  "/api/itineraries/[id]",
  "/api/itineraries/[id]/ai-backgrounds",
  "/api/itineraries/[id]/duplicate",
  "/api/itineraries/[id]/email",
  "/api/itineraries/[id]/export",
  "/api/itineraries/[id]/like",
  "/api/itineraries/[id]/notify-story-ready",
  "/api/itineraries/[id]/revise",
  "/api/itineraries/[id]/share",
  "/api/itineraries/[id]/story",
  "/api/itineraries/[id]/story/media/[generation]/[slide]",
  "/api/itineraries/[id]/story/persist",
  "/api/itineraries/[id]/story/save",
  "/api/itineraries/[id]/update",
  "/api/itineraries/generate",
  "/api/itineraries/generate-v2",
  "/api/itineraries/generate-v2/stream",
  "/api/itineraries/save",
  "/api/leaderboard",
  "/api/notifications",
  "/api/notifications/[id]",
  "/api/notifications/preferences",
  "/api/notifications/push/subscribe",
  "/api/og",
  "/api/places/photo",
  "/api/places/photos",
  "/api/recommendations",
  "/api/spots/[id]/photos",
  "/api/spots/[id]/reviews",
  "/api/spots/[id]/reviews/[reviewId]",
  "/api/spots/[id]/reviews/[reviewId]/helpful",
  "/api/spots/save",
  "/api/spots/social-submissions",
  "/api/spots/social-submissions/media-status",
  "/api/subscription/checkout",
  "/api/subscription/portal",
  "/api/subscription/status",
  "/api/subscription/webhook",
  "/api/test-app-data",
  "/api/test-app-data/chat-spots",
  "/api/test-app-data/chat-usage",
  "/api/test-app-data/spots",
  "/api/test-app-data/stories/[id]",
  "/api/test-app-data/story-background",
  "/api/test-auth/outbox",
  "/api/translate",
  "/api/user/email-preferences",
  "/api/user/saved-itineraries",
  "/api/user/tier",
  "/api/v2/trips/preview",
  "/api/viator/search",
  "/challenges",
  "/chat",
  "/dashboard",
  "/explore",
  "/forgot-password",
  "/guide/apply",
  "/guide/dashboard",
  "/itineraries",
  "/itineraries/[id]",
  "/itineraries/[id]/edit",
  "/itineraries/[id]/stories",
  "/itineraries/new",
  "/leaderboard",
  "/pricing",
  "/profile",
  "/reset-password",
  "/settings",
  "/shared/[shareCode]",
  "/sign-in/[[...sign-in]]",
  "/sign-up/[[...sign-up]]",
  "/sign-in",
  "/sign-up",
  "/spots",
  "/spots/[id]",
  "/spots/submissions",
  "/spots/submit",
  "/templates",
  "/users/[username]"
];
const patterns = routes.map(template => {
  const parts = template.split('/').slice(1);
  const output = []; const pattern = parts.map(part => {
    if (part.startsWith('[[...')) { output.push(':route'); return '(?:/[^/]+)*'; }
    if (part.startsWith('[...')) { output.push(':route'); return '(?:/[^/]+)+'; }
    if (part.startsWith('[')) { output.push(':' + part.slice(1,-1)); return '/[^/]+'; }
    output.push(part); return '/' + part.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }).join('');
  return { expression: new RegExp('^' + (pattern || '/') + '/?$'),
    route: '/' + output.join('/'), dynamic: template.includes('[') };
}).sort((a,b) => Number(a.dynamic) - Number(b.dynamic));

export function errorRouteGroup(value) {
  if (typeof value !== 'string' || value.length > 16384) return ':unknown-route';
  let path;
  try {
    const url = new URL(value);
    if (!['https:', 'http:'].includes(url.protocol)) return ':unknown-route';
    path = url.pathname;
  } catch { return ':unknown-route'; }
  // Encoded separators are not accepted as route structure.
  if (/%(?:2f|5c)/i.test(path) || path.includes('\\')) return ':unknown-route';
  return patterns.find(item => item.expression.test(path))?.route ?? ':unknown-route';
}
